FROM golang:1.24.5-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/app

FROM gcr.io/distroless/base-debian12
WORKDIR /
ENV APP_ENV=prod
ENV HTTP_PORT=:8080
COPY --from=builder /app/server /server
COPY --from=builder /app/api /api
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/server"]


